# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bARIQ0dcu4z5ObZY83ePCdzb7BApC6gj
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import numpy as np

# ─────────────────────────────────────────────────────────────────────────────
# Part 1: PrunableLinear Layer
# ─────────────────────────────────────────────────────────────────────────────

class PrunableLinear(nn.Module):


    def __init__(self, in_features: int, out_features: int):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features

        # Standard weight and bias parameters
        self.weight = nn.Parameter(torch.empty(out_features, in_features))
        self.bias   = nn.Parameter(torch.zeros(out_features))

        # Gate score tensor – same shape as weight, also a learnable parameter.
        # FIX: Initialize to -2.0 so sigmoid(-2) ≈ 0.12 — gates start nearly closed.
        # sigmoid(0) = 0.5 means gates start half-open, making it very hard for the
        # L1 penalty to push them all the way to zero. Starting at -2.0 means a
        # small sparsity gradient is already enough to close remaining gates.
        self.gate_scores = nn.Parameter(torch.full((out_features, in_features), -2.0))

        # Standard Kaiming initialisation for the weight matrix
        nn.init.kaiming_uniform_(self.weight, a=np.sqrt(5))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # Step 1: Compute gates in (0, 1) via Sigmoid
        gates = torch.sigmoid(self.gate_scores)          # shape: (out, in)

        # Step 2: Element-wise gate the weights
        pruned_weights = self.weight * gates             # shape: (out, in)

        # Step 3: Standard linear operation – gradients flow to weight AND gate_scores
        return F.linear(x, pruned_weights, self.bias)

    def get_gates(self) -> torch.Tensor:
        """Return the current gate values (detached, for analysis)."""
        return torch.sigmoid(self.gate_scores).detach()


# ─────────────────────────────────────────────────────────────────────────────
# Network Definition
# ─────────────────────────────────────────────────────────────────────────────

class SelfPruningNet(nn.Module):


    def __init__(self):
        super().__init__()
        input_dim = 3 * 32 * 32  # 3072

        self.net = nn.Sequential(
            PrunableLinear(input_dim, 1024),
            nn.BatchNorm1d(1024),
            nn.ReLU(),
            nn.Dropout(0.3),
            PrunableLinear(1024, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(),
            nn.Dropout(0.3),
            PrunableLinear(512, 256),
            nn.BatchNorm1d(256),
            nn.ReLU(),
            nn.Dropout(0.2),
            PrunableLinear(256, 10),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = x.view(x.size(0), -1)   # flatten
        return self.net(x)

    def prunable_layers(self):
        """Yield all PrunableLinear layers for gate inspection."""
        for module in self.modules():
            if isinstance(module, PrunableLinear):
                yield module


# ─────────────────────────────────────────────────────────────────────────────
# Part 2: Sparsity Loss
# ─────────────────────────────────────────────────────────────────────────────

def sparsity_loss(model: SelfPruningNet) -> torch.Tensor:

    total = torch.tensor(0.0, requires_grad=True)
    for layer in model.prunable_layers():
        gates = torch.sigmoid(layer.gate_scores)
        total = total + gates.sum()
    return total


# ─────────────────────────────────────────────────────────────────────────────
# Data Loading
# ─────────────────────────────────────────────────────────────────────────────

def get_dataloaders(batch_size: int = 128):
    # Data augmentation on train set → boosts accuracy by ~3-5%
    train_transform = transforms.Compose([
        transforms.RandomHorizontalFlip(),
        transforms.RandomCrop(32, padding=4),
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465),
                             (0.2470, 0.2435, 0.2616)),
    ])
    test_transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465),
                             (0.2470, 0.2435, 0.2616)),
    ])
    train_set = datasets.CIFAR10(root="./data", train=True,  download=True, transform=train_transform)
    test_set  = datasets.CIFAR10(root="./data", train=False, download=True, transform=test_transform)
    train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True,  num_workers=2, pin_memory=True)
    test_loader  = DataLoader(test_set,  batch_size=256,        shuffle=False, num_workers=2, pin_memory=True)
    return train_loader, test_loader


# ─────────────────────────────────────────────────────────────────────────────
# Part 3: Training Loop
# ─────────────────────────────────────────────────────────────────────────────

def train_one_epoch(model, loader, optimizer, device, lam, epoch, scheduler=None, warmup_epochs=10):

    effective_lam = lam * min(1.0, epoch / warmup_epochs)

    model.train()
    total_loss = 0.0
    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()

        logits = model(images)
        cls_loss = F.cross_entropy(logits, labels)
        sp_loss  = sparsity_loss(model)

        # Total loss = Classification loss + λ * Sparsity loss
        loss = cls_loss + effective_lam * sp_loss

        loss.backward()
        optimizer.step()

        # OneCycleLR must step every batch (not every epoch)
        if scheduler is not None:
            scheduler.step()

        total_loss += loss.item()
    return total_loss / len(loader)


# ─────────────────────────────────────────────────────────────────────────────
# Evaluation Helpers
# ─────────────────────────────────────────────────────────────────────────────

def evaluate(model, loader, device):
    """Returns test accuracy (%)."""
    model.eval()
    correct = total = 0
    with torch.no_grad():
        for images, labels in loader:
            images, labels = images.to(device), labels.to(device)
            preds = model(images).argmax(dim=1)
            correct += (preds == labels).sum().item()
            total   += labels.size(0)
    return 100.0 * correct / total


def compute_sparsity(model, threshold=0.1):

    all_gates = []
    for layer in model.prunable_layers():
        all_gates.append(layer.get_gates().flatten())
    all_gates = torch.cat(all_gates)
    pruned    = (all_gates < threshold).sum().item()
    return 100.0 * pruned / all_gates.numel(), all_gates.cpu().numpy()


# ─────────────────────────────────────────────────────────────────────────────
# Main Experiment
# ─────────────────────────────────────────────────────────────────────────────

def run_experiment(lam: float, epochs: int, device, train_loader, test_loader):
    print(f"\n{'='*55}")
    print(f"  Training with λ = {lam}  |  epochs = {epochs}")
    print(f"{'='*55}")

    model     = SelfPruningNet().to(device)
    optimizer = optim.Adam(model.parameters(), lr=3e-3, weight_decay=1e-4)
    # OneCycleLR: ramps lr up then down — reaches higher accuracy faster than
    # a flat lr. Works well with Adam and gives ~2-3% extra accuracy vs CosineAnnealing.
    scheduler = optim.lr_scheduler.OneCycleLR(
        optimizer, max_lr=3e-3,
        steps_per_epoch=len(train_loader), epochs=epochs,
        pct_start=0.2   # spend 20% ramping up, 80% decaying
    )

    for epoch in range(1, epochs + 1):
        loss = train_one_epoch(model, train_loader, optimizer, device, lam, epoch)
        scheduler.step()  # OneCycleLR steps per batch but we step per epoch here for simplicity
        if epoch % 5 == 0 or epoch == 1:
            acc = evaluate(model, test_loader, device)
            sp, _  = compute_sparsity(model)
            print(f"  Epoch {epoch:3d} | Loss {loss:.4f} | "
                  f"Test Acc {acc:.2f}% | Sparsity {sp:.1f}%")

            # Gate diagnostic — verify gates are actually moving
            if epoch == 1 or epoch % 10 == 0:
                print("  Gate diagnostics:")
                for i, layer in enumerate(model.prunable_layers()):
                    g = layer.get_gates().flatten()
                    print(f"    Layer {i+1}: min={g.min():.4f}  "
                          f"mean={g.mean():.4f}  max={g.max():.4f}  "
                          f"below_0.1={(g < 0.1).float().mean()*100:.1f}%")

    final_acc = evaluate(model, test_loader, device)
    sparsity, gate_vals = compute_sparsity(model)
    print(f"\n  Final  | Test Acc {final_acc:.2f}% | Sparsity {sparsity:.1f}%")
    return final_acc, sparsity, gate_vals, model


def plot_gate_distribution(gate_vals: np.ndarray, lam: float, ax):
    """Plot histogram of gate values for a given λ."""
    ax.hist(gate_vals, bins=100, color="steelblue", edgecolor="none", alpha=0.85)
    ax.set_title(f"Gate Distribution  (λ = {lam})", fontsize=11)
    ax.set_xlabel("Gate Value", fontsize=9)
    ax.set_ylabel("Count", fontsize=9)
    ax.axvline(x=0.1, color="red", linestyle="--", linewidth=1, label="Prune threshold (0.1)")
    ax.legend(fontsize=8)


def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    train_loader, test_loader = get_dataloaders(batch_size=256)

    # FIX: Stronger λ values produce visible sparsity.
    # Old values [1e-5, 1e-4, 1e-3] were too weak — the classification loss
    # completely dominated and gates never moved toward zero.
    lambdas = [1e-3, 1e-2, 1e-1]

    # FIX: 30 epochs was not enough — gates need time to drift toward zero
    # under the constant L1 pressure. 50 epochs gives clear bimodal distribution.
    epochs  = 10

    results      = {}   # lam -> (acc, sparsity, gate_vals)
    best_lam     = None
    best_acc     = -1

    for lam in lambdas:
        acc, sparsity, gate_vals, model = run_experiment(
            lam, epochs, device, train_loader, test_loader
        )
        results[lam] = (acc, sparsity, gate_vals)
        if acc > best_acc:
            best_acc  = acc
            best_lam  = lam
            best_gate = gate_vals

    # ── Summary Table ──────────────────────────────────────────────────────
    print("\n\n" + "="*55)
    print("  RESULTS SUMMARY")
    print("="*55)
    print(f"  {'Lambda':<12} {'Test Accuracy':>15} {'Sparsity Level':>16}")
    print("-"*55)
    for lam in lambdas:
        acc, sp, _ = results[lam]
        print(f"  {lam:<12} {acc:>14.2f}% {sp:>15.1f}%")
    print("="*55)

    # ── Gate Distribution Plots ────────────────────────────────────────────
    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    for ax, lam in zip(axes, lambdas):
        _, _, gate_vals = results[lam]
        plot_gate_distribution(gate_vals, lam, ax)

    plt.suptitle("Self-Pruning Neural Network – Gate Value Distributions",
                 fontsize=13, fontweight="bold")
    plt.tight_layout()
    plt.savefig("gate_distributions.png", dpi=150, bbox_inches="tight")
    print("\nPlot saved → gate_distributions.png")
    plt.show()


if __name__ == "__main__":
    main()

